name: Gitee repos mirror periodic job

on:
  # push:
    # branches:
      # - master
  # 手动事件
  workflow_dispatch:
  # 计划事件
  schedule:
    # 每天北京时间 9点 运行
    - cron:  '10 * * * *'

# 任务
jobs:
  build:
    # 服务器环境：最新版 Ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: Mirror the Github organization repos to Gitee.
        uses: Yikun/gitee-mirror-action@v0.10
        with:
          # 必选，需要同步的 Github 用户（源）
          src: github/colakele
          # 必选，需要同步到的 Gitee 用户（目的）
          dst: gitee/colakele
          # 必选，Gitee公钥对应的私钥，https://gitee.com/profile/sshkeys
          # id_rsa.pub: 公钥，id_rsa: 私钥
          dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
          # 必选，Gitee对应的用于创建仓库的token，https://gitee.com/profile/personal_access_tokens
          dst_token:  ${{ secrets.GITEE_TOKEN }}
          # 如果是组织，指定组织即可，默认为用户user
          # account_type: user
          # 还有黑、白名单，静态名单机制，可以用于更新某些指定库
          # static_list: "vue-admin-antd"
          # black_list: "repo_name,repo_name2"
          # white_list: "repo_name,repo_name2"
          force_update: true
          # debug: true
          # clone_style: "ssh"
